### ISSUE TITLE
Install instruction for hex archive

### ISSUE THREAD

**Issue by Tuxified** [gausby/workshop#10]
Until we can do a `mix hex.install workshop`, it would be nice to supply install instructions?
I know a `git clone && cd workshop && mix archive.build; mix archive.install workshop*.ez` will work, but it would be nice to include that in the docs since the archive is also needed for workshop attendees (for mix workshop.next etc.). 

Perhaps it's an idea to include a workshop-version.ez (in the generated workshop) so people who want to do a workshop don't need to take the extra step in installing it?

**Comment by gausby** [comment]
I agree. I will add some boilerplate install instructions to the generated README file.

I am really looking forward to `mix hex.install workshop`; it will make documentation so much easier.

**Comment by gausby** [comment]
I have to look into Phoenix's strategy for managing the ez-files; their solution is definitely better than my current solution: http://www.phoenixframework.org/docs/installation

Thanks for the suggestion.
