### ISSUE TITLE
[IDEA] Hooks / callbacks to extend functionality

### ISSUE THREAD

**Issue by Tuxified** [gausby/workshop#12]
I think it would be nice to add hooks / callbacks when certain events happen (for example completing an exercise). This would allow workshop builder to extend it with new functionality.

For example: I was thinking of adding a URL/server which would receive a message when someone completes an exercise. That way the workshop trainer could track progress across all workshop attendees without having to walk up to every attendee.

**Comment by gausby** [comment]
Could be cool. Let me see what I can come up with :)

**Comment by gausby** [comment]
@Tuxified how about this: #14 

If you define a public zero-arity function called `on_exercise_completed` on the given exercise (defined in the _exercise.exs_-file) it will get run when the given exercise change state from _in_progress_ to _completed_ (ie, going from _completed_ to _completed_ will not trigger the function again)

**Comment by gausby** [comment]
Please let me know if you have ideas for other hooks, and I'll add them, or make a PR. Thanks again for the suggestion.
